CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  address TEXT DEFAULT '',
  googleId VARCHAR(255) DEFAULT '',
  facebookId VARCHAR(255) DEFAULT '',
  profilePicture VARCHAR(500) DEFAULT '',
  otp VARCHAR(10) DEFAULT '',
  isVerified BOOLEAN DEFAULT FALSE,
  otpExpiry DATETIME DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);